In [1]:
import numpy as np
import torch
import pychop2 as pychop
from pychop2.chop import chop
from pychop2 import float_params
from time import time
from numpy import linalg
import jax
# from pychop.chop import chop
# from pychop.quant import quant
from time import time
np.random.seed(0)

In [2]:
X_np = np.random.randn(10000, 5000) # Numpy array
X_th = torch.Tensor(X_np) # torch array
X_jx = jax.numpy.asarray(X_np)
print(X_np)

[[ 1.76405235  0.40015721  0.97873798 ...  0.92918181  0.22941801
   0.41440588]
 [ 0.30972382 -0.73745619 -1.53691988 ...  0.51687218 -0.03292069
   1.29811143]
 [-0.20211703 -0.833231    1.73360025 ...  0.75309415 -0.58103281
  -0.19837974]
 ...
 [-0.95937066 -1.01246716  0.34880668 ... -0.35084245 -1.22737575
  -0.91013657]
 [ 0.47916694  0.14827316  1.43757655 ...  0.81176824  1.34234704
   0.1326462 ]
 [ 0.35617281 -0.31372555 -0.60923753 ... -0.18023451 -2.84566402
  -0.4275742 ]]


### print unit-roundoff in machine

In [3]:


float_params()

u      xmins       xmin       xmax    p    emins     emin  \
0  q43   6.25e-02   1.95e-03   1.56e-02   2.40e+02    4       -9       -6   
1  q52   1.25e-01   1.53e-05   6.10e-05   5.73e+04    3      -16      -14   
2    b   3.91e-03   9.18e-41   1.18e-38   3.39e+38    8     -133     -126   
3    h   4.88e-04   5.96e-08   6.10e-05   6.55e+04   11      -24      -14   
4    t   4.88e-04   1.15e-41   1.18e-38   3.40e+38   11     -136     -126   
5    s   5.96e-08   1.40e-45   1.18e-38   3.40e+38   24     -149     -126   
6    d   1.11e-16  4.94e-324  2.23e-308  1.80e+308   53    -1074    -1022   
7    q   9.63e-35   0.00e+00   0.00e+00        inf  113   -16494   -16382   

     emax  
0       7  
1      15  
2     127  
3      15  
4     127  
5     127  
6    1023  
7   16383

### set backend

In [4]:
pychop.backend('torch')

In [7]:
pychop.backend('numpy', 1) # print information, NumPy is the default option.

Load NumPy backend.


### run chop

In [8]:
pyq_f = chop('h')

In [9]:
st = time()
X_bit = pyq_f(X_np)
print("runtime:", time() - st)
print(X_bit)

runtime: 3.900692939758301
[[ 1.76367188  0.40014648  0.97851562 ...  0.92919922  0.22937012
   0.41430664]
 [ 0.30981445 -0.73730469 -1.53710938 ...  0.51708984 -0.03292847
   1.29785156]
 [-0.20214844 -0.83300781  1.73339844 ...  0.75292969 -0.58105469
  -0.19836426]
 ...
 [-0.95947266 -1.01269531  0.34887695 ... -0.35083008 -1.22753906
  -0.91015625]
 [ 0.47924805  0.14831543  1.4375     ...  0.81201172  1.34277344
   0.13269043]
 [ 0.35620117 -0.3137207  -0.609375   ... -0.18017578 -2.84570312
  -0.42749023]]


In [10]:
from pychop2.chop import chop
from time import time

pyq_f = chop('h')
st = time()
X_bit = pyq_f(X_np)

print("runtime:", time() - st)
print(X_bit)

runtime: 4.140857219696045
[[ 1.76367188  0.40014648  0.97851562 ...  0.92919922  0.22937012
   0.41430664]
 [ 0.30981445 -0.73730469 -1.53710938 ...  0.51708984 -0.03292847
   1.29785156]
 [-0.20214844 -0.83300781  1.73339844 ...  0.75292969 -0.58105469
  -0.19836426]
 ...
 [-0.95947266 -1.01269531  0.34887695 ... -0.35083008 -1.22753906
  -0.91015625]
 [ 0.47924805  0.14831543  1.4375     ...  0.81201172  1.34277344
   0.13269043]
 [ 0.35620117 -0.3137207  -0.609375   ... -0.18017578 -2.84570312
  -0.42749023]]


In [5]:
from pychop2.bitchop import bitchop
pychop.backend('numpy')

pyq_f = bitchop(exp_bits=5, sig_bits=10, rmode=1, subnormal=False, random_state=42, device="cpu", verbose=0)
st = time()
X_bit = pyq_f(X_np)
print("runtime:", time() - st)
print(X_bit)

runtime: 141.34492301940918
[[ 1.76367188  0.40014648  0.97851562 ...  0.92871094  0.22937012
   0.41430664]
 [ 0.30957031 -0.73730469 -1.53710938 ...  0.51660156 -0.03289795
   1.29785156]
 [-0.20214844 -0.83300781  1.73339844 ...  0.75292969 -0.58105469
  -0.19836426]
 ...
 [-0.95898438 -1.01171875  0.34863281 ... -0.35083008 -1.2265625
  -0.91015625]
 [ 0.47900391  0.14819336  1.4375     ...  0.81152344  1.34179688
   0.13256836]
 [ 0.35595703 -0.3137207  -0.609375   ... -0.18017578 -2.84375
  -0.42749023]]


In [ ]:
print("2^"+str(int(np.log2(pyq_f.u))))

In [4]:
pychop.backend('torch', 1) # print information
pyq_f = chop('h')
st = time()
X_bit = pyq_f(X_th)
print("runtime:", time() - st)
print(X_bit)

Load Troch backend.
runtime: 2.3097269535064697
tensor([[ 1.7637,  0.4001,  0.9785,  ...,  0.9292,  0.2294,  0.4143],
        [ 0.3098, -0.7373, -1.5371,  ...,  0.5171, -0.0329,  1.2979],
        [-0.2021, -0.8330,  1.7334,  ...,  0.7529, -0.5811, -0.1984],
        ...,
        [-0.9595, -1.0127,  0.3489,  ..., -0.3508, -1.2275, -0.9102],
        [ 0.4792,  0.1483,  1.4375,  ...,  0.8120,  1.3428,  0.1327],
        [ 0.3562, -0.3137, -0.6094,  ..., -0.1802, -2.8457, -0.4275]])


In [12]:
pychop.backend('torch', 1) # print information
pyq_f = chop('h')
st = time()
X_bit = pyq_f(X_th)
print("runtime:", time() - st)
print(X_bit)

Load Troch backend.
runtime: 1.618636131286621
tensor([[ 1.7637,  0.4001,  0.9785,  ...,  0.9292,  0.2294,  0.4143],
        [ 0.3098, -0.7373, -1.5371,  ...,  0.5171, -0.0329,  1.2979],
        [-0.2021, -0.8330,  1.7334,  ...,  0.7529, -0.5811, -0.1984],
        ...,
        [-0.9595, -1.0127,  0.3489,  ..., -0.3508, -1.2275, -0.9102],
        [ 0.4792,  0.1483,  1.4375,  ...,  0.8120,  1.3428,  0.1327],
        [ 0.3562, -0.3137, -0.6094,  ..., -0.1802, -2.8457, -0.4275]])


In [5]:
pychop.backend('torch', 1) # print information
pyq_f = chop('h')
st = time()
X_bit = pyq_f(X_th)
print("runtime:", time() - st)
print(X_bit)

Load Troch backend.
runtime: 1.661458969116211
tensor([[ 1.7637,  0.4001,  0.9785,  ...,  0.9292,  0.2294,  0.4143],
        [ 0.3098, -0.7373, -1.5371,  ...,  0.5171, -0.0329,  1.2979],
        [-0.2021, -0.8330,  1.7334,  ...,  0.7529, -0.5811, -0.1984],
        ...,
        [-0.9595, -1.0127,  0.3489,  ..., -0.3508, -1.2275, -0.9102],
        [ 0.4792,  0.1483,  1.4375,  ...,  0.8120,  1.3428,  0.1327],
        [ 0.3562, -0.3137, -0.6094,  ..., -0.1802, -2.8457, -0.4275]])


In [5]:
pychop.backend('torch', 1) # print information
pyq_f = chop('h')
st = time()
X_bit = pyq_f(X_th)
print("runtime:", time() - st)
print(X_bit)

Load Troch backend.
runtime: 1.7425360679626465
tensor([[1.7637, 0.4001, 0.9785,  ..., 0.9292, 0.2294, 0.4143],
        [0.3098, 0.7373, 1.5371,  ..., 0.5171, 0.0329, 1.2979],
        [0.2021, 0.8330, 1.7334,  ..., 0.7529, 0.5811, 0.1984],
        ...,
        [0.9595, 1.0127, 0.3489,  ..., 0.3508, 1.2275, 0.9102],
        [0.4792, 0.1483, 1.4375,  ..., 0.8120, 1.3428, 0.1327],
        [0.3562, 0.3137, 0.6094,  ..., 0.1802, 2.8457, 0.4275]])


In [3]:
pychop.backend('jax', 1) # print information

pyq_f = chop('h')


Load JAX backend.


In [5]:
st = time()
X_bit = pyq_f(X_jx)
print("runtime:", time() - st)
print(X_bit)

runtime: 15.599064111709595
[[ 1.7636719   0.40014648  0.9785156  ...  0.9291992   0.22937012
   0.41430664]
 [ 0.30981445 -0.7373047  -1.5371094  ...  0.51708984 -0.03292847
   1.2978516 ]
 [-0.20214844 -0.8330078   1.7333984  ...  0.7529297  -0.5810547
  -0.19836426]
 ...
 [-0.95947266 -1.0126953   0.34887695 ... -0.35083008 -1.2275391
  -0.91015625]
 [ 0.47924805  0.14831543  1.4375     ...  0.8120117   1.3427734
   0.13269043]
 [ 0.35620117 -0.3137207  -0.609375   ... -0.18017578 -2.8457031
  -0.42749023]]


In [ ]:
pychop.backend('jax', 1) # print information
st = time()
pyq_f = chop('h')
X_bit = pyq_f(X_jx)
print("runtime:", time() - st)
print(X_bit)

In [ ]:
from pychop.chop import chop
pychop.backend('numpy')
pyq_f = chop('h', rmode=5, flip=0)
pyq_f(X_np)

### integer quantization

In [ ]:
pychop.backend('numpy')
pyq_f = pychop.quant(bits=8)
X_q = pyq_f(X_np)
X_inv = pyq_f.dequant(X_q)
linalg.norm(X_inv - X_np)

In [ ]:
pychop.backend('torch')
pyq_f = pychop.quant(bits=8)
X_q = pyq_f(X_th)
X_inv = pyq_f.dequant(X_q)
linalg.norm(X_inv - X_np)

In [ ]:
pychop.backend('jax')
pyq_f = pychop.quant(bits=8)
X_q = pyq_f(X_jx)
X_inv = pyq_f.dequant(X_q)
linalg.norm(X_inv - X_jx)

### fixed point quantization

In [ ]:
pychop.backend('numpy')
pyq_f = pychop.fpoint()

pyq_f(X_np)

In [ ]:
pychop.backend('torch')
pyq_f = pychop.fpoint()
pyq_f(X_th)

In [ ]:
pychop.backend('jax')
pyq_f = pychop.fpoint()
pyq_f(X_jx)