In [1]:
import numpy as np
import torch
import pychop as pychop
from pychop.chop import chop
from pychop import float_params
from time import time
from numpy import linalg
import jax
# from pychop.chop import chop
# from pychop.quant import quant
from time import time
from scipy.io import savemat
# np.set_printoptions(precision=19)

In [2]:
np.random.seed(0)

X_np = np.random.randn(5000, 5000) # Numpy array
X_th = torch.Tensor(X_np) # torch array
X_jx = jax.numpy.asarray(X_np)
print(X_np)

#savemat("tests/verify.mat", {"X":X_np})

[[ 1.76405235  0.40015721  0.97873798 ...  0.92918181  0.22941801
   0.41440588]
 [ 0.30972382 -0.73745619 -1.53691988 ...  0.51687218 -0.03292069
   1.29811143]
 [-0.20211703 -0.833231    1.73360025 ...  0.75309415 -0.58103281
  -0.19837974]
 ...
 [ 1.07432182  1.188486    0.5092741  ...  0.07053449  0.59975911
  -2.41029925]
 [ 0.32432475 -0.02337844  1.62873399 ... -0.16088168 -1.59772992
   1.414703  ]
 [ 0.63460807  1.38090977  0.54829109 ...  0.30762729 -0.11078251
   0.83859307]]


In [12]:
X_th[0:5, 0]

tensor([ 1.7641,  0.3097, -0.2021,  2.4700,  0.3300])

### print unit-roundoff in machine

In [3]:
float_params()

u      xmins       xmin       xmax    p    emins     emin  \
0  q43   6.25e-02   1.95e-03   1.56e-02   2.40e+02    4       -9       -6   
1  q52   1.25e-01   1.53e-05   6.10e-05   5.73e+04    3      -16      -14   
2    b   3.91e-03   9.18e-41   1.18e-38   3.39e+38    8     -133     -126   
3    h   4.88e-04   5.96e-08   6.10e-05   6.55e+04   11      -24      -14   
4    t   4.88e-04   1.15e-41   1.18e-38   3.40e+38   11     -136     -126   
5    s   5.96e-08   1.40e-45   1.18e-38   3.40e+38   24     -149     -126   
6    d   1.11e-16  4.94e-324  2.23e-308  1.80e+308   53    -1074    -1022   
7    q   9.63e-35   0.00e+00   0.00e+00        inf  113   -16494   -16382   

     emax  
0       7  
1      15  
2     127  
3      15  
4     127  
5     127  
6    1023  
7   16383

### set backend

In [4]:
# pychop.backend('torch')
pychop.backend('numpy', 1) # print information, NumPy is the default option.

Load NumPy backend.


### run chop

In [13]:
pyq_f = chop('h')
st = time()
X_bit = pyq_f(X_np)
print("runtime:", time() - st)
print(X_bit[:10, 0])

runtime: 2.001610040664673
tensor([ 1.7637,  0.3098, -0.2021,  2.4707,  0.3301,  0.3020,  0.3713,  0.3872,
        -1.9395,  0.5615])


In [3]:
pychop.backend('torch', 1) # print information
pyq_f = chop('h', rmode=1)
st = time()
X_bit = pyq_f(X_th)
print("runtime:", time() - st)
print(X_bit[:10, 0])

Load Troch backend.
runtime: 1.8302061557769775
tensor([ 1.7637,  0.3098, -0.2021,  2.4707,  0.3301,  0.3020,  0.3713,  0.3872,
        -1.9395,  0.5615])


In [17]:
pychop.backend('torch', 1) # print information
pyq_f = chop('h', rmode=2)
st = time()
X_bit = pyq_f(X_th)
print("runtime:", time() - st)
print(X_bit[:10, 0])

Load Troch backend.
runtime: 1.3260867595672607
tensor([ 1.7646,  0.3098, -0.2020,  2.4707,  0.3301,  0.3022,  0.3713,  0.3875,
        -1.9395,  0.5620])


In [18]:
pychop.backend('torch', 1) # print information
pyq_f = chop('h', rmode=3)
st = time()
X_bit = pyq_f(X_th)
print("runtime:", time() - st)
print(X_bit[:10, 0])

Load Troch backend.
runtime: 0.8530240058898926
tensor([ 1.7637,  0.3096, -0.2021,  2.4688,  0.3298,  0.3020,  0.3711,  0.3872,
        -1.9404,  0.5615])


In [20]:
pychop.backend('torch', 1) # print information
pyq_f = chop('h', rmode=4)
st = time()
X_bit = pyq_f(X_th)
print("runtime:", time() - st)
print(X_bit[:10, 0])

Load Troch backend.
runtime: 1.5211341381072998
tensor([ 1.7637,  0.3096, -0.2020,  2.4688,  0.3298,  0.3020,  0.3711,  0.3872,
        -1.9395,  0.5615])


In [19]:
nearest             : tensor([ 1.7637,  0.3098, -0.2021,  2.4707,  0.3301])
up                  : tensor([ 1.7646,  0.3098, -0.2020,  2.4707,  0.3301])
down                : tensor([ 1.7637,  0.3096, -0.2021,  2.4688,  0.3298])
towards_zero        : tensor([ 1.7637,  0.3096, -0.2020,  2.4688,  0.3298])

tensor([[ 1.7641,  0.4002,  0.9787,  ...,  0.9292,  0.2294,  0.4144],
        [ 0.3097, -0.7375, -1.5369,  ...,  0.5169, -0.0329,  1.2981],
        [-0.2021, -0.8332,  1.7336,  ...,  0.7531, -0.5810, -0.1984],
        ...,
        [ 1.0743,  1.1885,  0.5093,  ...,  0.0705,  0.5998, -2.4103],
        [ 0.3243, -0.0234,  1.6287,  ..., -0.1609, -1.5977,  1.4147],
        [ 0.6346,  1.3809,  0.5483,  ...,  0.3076, -0.1108,  0.8386]])

In [1]:
import torch
import numpy as np
from typing import Tuple


class FloatPrecisionSimulator:
    """
    A class to simulate different floating-point precisions and rounding modes
    for PyTorch tensors.
    """
    def __init__(self, exponent_bits: int, mantissa_bits: int):
        self.exponent_bits = exponent_bits
        self.mantissa_bits = mantissa_bits
        self.max_exp = 2 ** (exponent_bits - 1) - 1
        self.min_exp = -self.max_exp + 1
        self.bias = 2 ** (exponent_bits - 1) - 1  # Bias for IEEE 754
        
    def _to_custom_float(self, x: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor, 
                                                        torch.Tensor, torch.Tensor, torch.Tensor]:
        """
        Initialize with specific format parameters.
        Convert to custom float representation with proper IEEE 754 handling
        
        Args:
            exponent_bits: Number of bits for exponent
            mantissa_bits: Number of bits for mantissa (significant digits)
        """
        sign = torch.sign(x)
        abs_x = torch.abs(x)
        
        # Handle special cases
        zero_mask = (abs_x == 0)
        inf_mask = torch.isinf(x)
        nan_mask = torch.isnan(x)
        
        # Calculate raw exponent and mantissa
        exponent = torch.floor(torch.log2(abs_x.clamp(min=2.0**-24)))  # Minimum denormal
        
        # Normalize mantissa to [1, 2)
        mantissa = abs_x / (2.0 ** exponent)
        
        # Handle subnormals
        subnormal_mask = (exponent < self.min_exp)
        if torch.any(subnormal_mask):
            mantissa[subnormal_mask] = abs_x[subnormal_mask] / (2.0 ** self.min_exp)
            exponent[subnormal_mask] = self.min_exp
        
        return sign, exponent + self.bias, mantissa, zero_mask, inf_mask, nan_mask
    
    def _quantize_components(self, 
                           x: torch.Tensor,
                           sign: torch.Tensor, 
                           exponent: torch.Tensor, 
                           mantissa: torch.Tensor,
                           zero_mask: torch.Tensor,
                           inf_mask: torch.Tensor,
                           nan_mask: torch.Tensor,
                           rounding_mode: str) -> torch.Tensor:
        """Quantize components according to IEEE 754 FP16 rules with various rounding modes"""
        
        # Clamp exponent to representable range (including bias)
        exp_min = 0  # 0 represents subnormals
        exp_max = 2**self.exponent_bits - 1  # 31 for FP16
        exponent = exponent.clamp(min=exp_min, max=exp_max)
        
        # Quantize mantissa
        mantissa_steps = 2 ** self.mantissa_bits
        normal_mask = (exponent > 0) & (exponent < exp_max)
        subnormal_mask = (exponent == 0)
        mantissa_normal = mantissa - 1.0  # Remove implicit leading 1 for normal numbers
        
        # Apply rounding mode
        if rounding_mode == "nearest":
            mantissa_q = torch.round(mantissa_normal * mantissa_steps) / mantissa_steps
            if torch.any(subnormal_mask):
                mantissa_q[subnormal_mask] = torch.round(mantissa[subnormal_mask] * 
                                                       mantissa_steps) / mantissa_steps
        elif rounding_mode == "up":
            mantissa_q = torch.where(sign > 0, 
                                   torch.ceil(mantissa_normal * mantissa_steps),
                                   torch.floor(mantissa_normal * mantissa_steps)) / mantissa_steps
            if torch.any(subnormal_mask):
                mantissa_q[subnormal_mask] = torch.where(sign[subnormal_mask] > 0,
                                                       torch.ceil(mantissa[subnormal_mask] * mantissa_steps),
                                                       torch.floor(mantissa[subnormal_mask] * mantissa_steps)) / mantissa_steps
        elif rounding_mode == "down":
            mantissa_q = torch.where(sign > 0,
                                   torch.floor(mantissa_normal * mantissa_steps),
                                   torch.ceil(mantissa_normal * mantissa_steps)) / mantissa_steps
            if torch.any(subnormal_mask):
                mantissa_q[subnormal_mask] = torch.where(sign[subnormal_mask] > 0,
                                                       torch.floor(mantissa[subnormal_mask] * mantissa_steps),
                                                       torch.ceil(mantissa[subnormal_mask] * mantissa_steps)) / mantissa_steps
        elif rounding_mode == "towards_zero":
            mantissa_q = torch.trunc(mantissa_normal * mantissa_steps) / mantissa_steps
            if torch.any(subnormal_mask):
                mantissa_q[subnormal_mask] = torch.trunc(mantissa[subnormal_mask] * 
                                                       mantissa_steps) / mantissa_steps
        elif rounding_mode == "stochastic_equal":
            mantissa_scaled = mantissa_normal * mantissa_steps
            floor_val = torch.floor(mantissa_scaled)
            prob = torch.rand_like(mantissa_scaled)
            mantissa_q = torch.where(prob < 0.5, floor_val, floor_val + 1) / mantissa_steps
            if torch.any(subnormal_mask):
                mantissa_scaled = mantissa[subnormal_mask] * mantissa_steps
                floor_val = torch.floor(mantissa_scaled)
                prob = torch.rand_like(mantissa_scaled)
                mantissa_q[subnormal_mask] = torch.where(prob < 0.5, floor_val, 
                                                       floor_val + 1) / mantissa_steps
        elif rounding_mode == "stochastic_proportional":
            mantissa_scaled = mantissa_normal * mantissa_steps
            floor_val = torch.floor(mantissa_scaled)
            fraction = mantissa_scaled - floor_val
            prob = torch.rand_like(mantissa_scaled)
            mantissa_q = torch.where(prob < fraction, floor_val + 1, floor_val) / mantissa_steps
            if torch.any(subnormal_mask):
                mantissa_scaled = mantissa[subnormal_mask] * mantissa_steps
                floor_val = torch.floor(mantissa_scaled)
                fraction = mantissa_scaled - floor_val
                prob = torch.rand_like(mantissa_scaled)
                mantissa_q[subnormal_mask] = torch.where(prob < fraction, floor_val + 1, 
                                                       floor_val) / mantissa_steps
        else:
            raise ValueError(f"Unsupported rounding mode: {rounding_mode}")
        
        # Reconstruct the number
        result = torch.zeros_like(x)
        
        # Normal numbers
        if torch.any(normal_mask):
            result[normal_mask] = sign[normal_mask] * (1.0 + mantissa_q[normal_mask]) * \
                                (2.0 ** (exponent[normal_mask] - self.bias))
        
        # Subnormal numbers
        if torch.any(subnormal_mask):
            result[subnormal_mask] = sign[subnormal_mask] * mantissa_q[subnormal_mask] * \
                                   (2.0 ** self.min_exp)
        
        # Special cases
        result[zero_mask] = 0.0
        result[inf_mask] = torch.sign(x[inf_mask]) * float('inf')
        result[nan_mask] = float('nan')
        
        return result

    def quantize(self, x: torch.Tensor, rounding_mode: str = "nearest") -> torch.Tensor:
        """
        Quantize a tensor to the specified precision with given rounding mode.
        
        Args:
            x: Input tensor
            rounding_mode: One of 'nearest', 'up', 'down', 'towards_zero', 
                          'stochastic_equal', 'stochastic_proportional'
        """
        sign, exponent, mantissa, zero_mask, inf_mask, nan_mask = self._to_custom_float(x)
        return self._quantize_components(x, sign, exponent, mantissa, zero_mask, inf_mask, nan_mask, rounding_mode)


class QuantizedLayer(torch.nn.Module):
    """Example of a quantized linear layer"""
    def __init__(self, 
                 in_features: int, 
                 out_features: int,
                 exponent_bits: int,
                 mantissa_bits: int,
                 rounding_mode: str = "nearest"):
        super().__init__()
        self.quantizer = FloatPrecisionSimulator(exponent_bits, mantissa_bits)
        self.weight = torch.nn.Parameter(torch.randn(out_features, in_features))
        self.bias = torch.nn.Parameter(torch.randn(out_features))
        self.rounding_mode = rounding_mode
        
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # Quantize weights and input
        q_weight = self.quantizer.quantize(self.weight, self.rounding_mode)
        q_input = self.quantizer.quantize(x, self.rounding_mode)
        
        # Perform computation
        output = torch.matmul(q_input, q_weight.t())
        
        # Quantize bias and add
        q_bias = self.quantizer.quantize(self.bias, self.rounding_mode)
        output = output + q_bias
        
        return output

# Example usage
def main():
    # Define some common formats
    formats = {
        "fp32": (8, 23),    # Standard IEEE 754 float32
        "fp16": (5, 10),    # Standard IEEE 754 float16
        "bf16": (8, 7),     # Brain Float 16
        "fp8": (5, 2),      # Example 8-bit float
    }
    
    # Test different rounding modes
    rounding_modes = [
        "nearest",
        "up",
        "down",
        "towards_zero",
        "stochastic_equal",
        "stochastic_proportional"
    ]
    
    # Create a sample tensor
    x = torch.tensor([0.1, 0.3, 1.7, 3.9, -2.5])
    
    # Test quantization
    simulator = FloatPrecisionSimulator(*formats["fp16"])
    
    print("Original values:", x)
    for mode in rounding_modes:
        result = simulator.quantize(x, mode)
        print(f"{mode}:", result)

    # Test with a layer
    layer = QuantizedLayer(4, 2, *formats["bf16"], rounding_mode="nearest")
    input_tensor = torch.randn(3, 4)
    output = layer(input_tensor)
    print("\nLayer output shape:", output.shape)

if __name__ == "__main__":
    main()

Original values: tensor([ 0.1000,  0.3000,  1.7000,  3.9000, -2.5000])
nearest: tensor([ 0.1000,  0.3000,  1.7002,  3.9004, -2.5000])
up: tensor([ 0.1000,  0.3000,  1.7002,  3.9004, -2.5000])
down: tensor([ 0.1000,  0.2998,  1.6992,  3.8984, -2.5000])
towards_zero: tensor([ 0.1000,  0.2998,  1.6992,  3.8984, -2.5000])
stochastic_equal: tensor([ 0.1000,  0.3000,  1.7002,  3.8984, -2.5000])
stochastic_proportional: tensor([ 0.1000,  0.3000,  1.7002,  3.9004, -2.5000])

Layer output shape: torch.Size([3, 2])


In [6]:
import torch
import numpy as np
from typing import Tuple

class FloatPrecisionSimulator:
    """
    A class to simulate different floating-point precisions and rounding modes
    for PyTorch tensors.
    """
    def __init__(self, exponent_bits: int, mantissa_bits: int):
        self.exponent_bits = exponent_bits
        self.mantissa_bits = mantissa_bits
        self.max_exp = 2 ** (exponent_bits - 1) - 1
        self.min_exp = -self.max_exp + 1
        self.bias = 2 ** (exponent_bits - 1) - 1  # Bias for IEEE 754
        
    def _to_custom_float(self, x: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor, 
                                                        torch.Tensor, torch.Tensor, torch.Tensor]:
        """
        Initialize with specific format parameters.
        Convert to custom float representation with proper IEEE 754 handling
        
        Args:
            exponent_bits: Number of bits for exponent
            mantissa_bits: Number of bits for mantissa (significant digits)
        """
        sign = torch.sign(x)
        abs_x = torch.abs(x)
        
        # Handle special cases
        zero_mask = (abs_x == 0)
        inf_mask = torch.isinf(x)
        nan_mask = torch.isnan(x)
        
        # Calculate raw exponent and mantissa
        exponent = torch.floor(torch.log2(abs_x.clamp(min=2.0**-24)))  # Minimum denormal
        
        # Normalize mantissa to [1, 2)
        mantissa = abs_x / (2.0 ** exponent)
        
        # Handle subnormals
        subnormal_mask = (exponent < self.min_exp)
        if torch.any(subnormal_mask):
            mantissa[subnormal_mask] = abs_x[subnormal_mask] / (2.0 ** self.min_exp)
            exponent[subnormal_mask] = self.min_exp
        
        return sign, exponent + self.bias, mantissa, zero_mask, inf_mask, nan_mask
    
    def _quantize_components(self, 
                           x: torch.Tensor,
                           sign: torch.Tensor, 
                           exponent: torch.Tensor, 
                           mantissa: torch.Tensor,
                           zero_mask: torch.Tensor,
                           inf_mask: torch.Tensor,
                           nan_mask: torch.Tensor,
                           rounding_mode: str) -> torch.Tensor:
        """Quantize components according to IEEE 754 FP16 rules with various rounding modes"""
        
        # Clamp exponent to representable range (including bias)
        exp_min = 0  # 0 represents subnormals
        exp_max = 2**self.exponent_bits - 1  # 31 for FP16
        exponent = exponent.clamp(min=exp_min, max=exp_max)
        
        # Quantize mantissa
        mantissa_steps = 2 ** self.mantissa_bits
        normal_mask = (exponent > 0) & (exponent < exp_max)
        subnormal_mask = (exponent == 0)
        mantissa_normal = mantissa - 1.0  # Remove implicit leading 1 for normal numbers
        
        # Apply rounding mode
        if rounding_mode == "nearest":
            mantissa_q = torch.round(mantissa_normal * mantissa_steps) / mantissa_steps
            if torch.any(subnormal_mask):
                mantissa_q[subnormal_mask] = torch.round(mantissa[subnormal_mask] * 
                                                       mantissa_steps) / mantissa_steps
        elif rounding_mode == "up":
            mantissa_q = torch.where(sign > 0, 
                                   torch.ceil(mantissa_normal * mantissa_steps),
                                   torch.floor(mantissa_normal * mantissa_steps)) / mantissa_steps
            if torch.any(subnormal_mask):
                mantissa_q[subnormal_mask] = torch.where(sign[subnormal_mask] > 0,
                                                       torch.ceil(mantissa[subnormal_mask] * mantissa_steps),
                                                       torch.floor(mantissa[subnormal_mask] * mantissa_steps)) / mantissa_steps
        elif rounding_mode == "down":
            mantissa_q = torch.where(sign > 0,
                                   torch.floor(mantissa_normal * mantissa_steps),
                                   torch.ceil(mantissa_normal * mantissa_steps)) / mantissa_steps
            if torch.any(subnormal_mask):
                mantissa_q[subnormal_mask] = torch.where(sign[subnormal_mask] > 0,
                                                       torch.floor(mantissa[subnormal_mask] * mantissa_steps),
                                                       torch.ceil(mantissa[subnormal_mask] * mantissa_steps)) / mantissa_steps
        elif rounding_mode == "towards_zero":
            mantissa_q = torch.trunc(mantissa_normal * mantissa_steps) / mantissa_steps
            if torch.any(subnormal_mask):
                mantissa_q[subnormal_mask] = torch.trunc(mantissa[subnormal_mask] * 
                                                       mantissa_steps) / mantissa_steps
        elif rounding_mode == "stochastic_equal":
            mantissa_scaled = mantissa_normal * mantissa_steps
            floor_val = torch.floor(mantissa_scaled)
            prob = torch.rand_like(mantissa_scaled)
            mantissa_q = torch.where(prob < 0.5, floor_val, floor_val + 1) / mantissa_steps
            if torch.any(subnormal_mask):
                mantissa_scaled = mantissa[subnormal_mask] * mantissa_steps
                floor_val = torch.floor(mantissa_scaled)
                prob = torch.rand_like(mantissa_scaled)
                mantissa_q[subnormal_mask] = torch.where(prob < 0.5, floor_val, 
                                                       floor_val + 1) / mantissa_steps
        elif rounding_mode == "stochastic_proportional":
            mantissa_scaled = mantissa_normal * mantissa_steps
            floor_val = torch.floor(mantissa_scaled)
            fraction = mantissa_scaled - floor_val
            prob = torch.rand_like(mantissa_scaled)
            mantissa_q = torch.where(prob < fraction, floor_val + 1, floor_val) / mantissa_steps
            if torch.any(subnormal_mask):
                mantissa_scaled = mantissa[subnormal_mask] * mantissa_steps
                floor_val = torch.floor(mantissa_scaled)
                fraction = mantissa_scaled - floor_val
                prob = torch.rand_like(mantissa_scaled)
                mantissa_q[subnormal_mask] = torch.where(prob < fraction, floor_val + 1, 
                                                       floor_val) / mantissa_steps
        else:
            raise ValueError(f"Unsupported rounding mode: {rounding_mode}")
        
        # Reconstruct the number
        result = torch.zeros_like(x)
        
        # Normal numbers
        if torch.any(normal_mask):
            result[normal_mask] = sign[normal_mask] * (1.0 + mantissa_q[normal_mask]) * \
                                (2.0 ** (exponent[normal_mask] - self.bias))
        
        # Subnormal numbers
        if torch.any(subnormal_mask):
            result[subnormal_mask] = sign[subnormal_mask] * mantissa_q[subnormal_mask] * \
                                   (2.0 ** self.min_exp)
        
        # Special cases
        result[zero_mask] = 0.0
        result[inf_mask] = torch.sign(x[inf_mask]) * float('inf')
        result[nan_mask] = float('nan')
        
        return result

    def quantize(self, x: torch.Tensor, rounding_mode: str = "nearest") -> torch.Tensor:
        """
        Quantize a tensor to the specified precision with given rounding mode.
        
        Args:
            x: Input tensor
            rounding_mode: One of 'nearest', 'up', 'down', 'towards_zero', 
                          'stochastic_equal', 'stochastic_proportional'
        """
        sign, exponent, mantissa, zero_mask, inf_mask, nan_mask = self._to_custom_float(x)
        return self._quantize_components(x, sign, exponent, mantissa, zero_mask, inf_mask, nan_mask, rounding_mode)

# Test the implementation
def test_fp16():
    # Test values
    values = torch.tensor([1.7641, 0.3097, -0.2021, 2.4700, 0.3300])
    
    # FP16 simulator (5 exponent bits, 10 mantissa bits)
    fp16_sim = FloatPrecisionSimulator(5, 10)
    
    # Test all rounding modes
    rounding_modes = ["nearest", "up", "down", "towards_zero", 
                     "stochastic_equal", "stochastic_proportional"]
    
    # Compare with PyTorch's native FP16
    fp16_native = values.to(dtype=torch.float16).to(dtype=torch.float32)
    
    print("Input values:      ", values)
    print("PyTorch FP16:      ", fp16_native)
    print()

    print("Your output:")
    for mode in rounding_modes[:4]:
        result = fp16_sim.quantize(values, mode)
        print(f"{mode:20}: {result}")
    

    print()
    rounding_modes_num = [1, 2, 3, 4, 
                     "stochastic_equal", "stochastic_proportional"]

    print("Correct ones:")
    for mode in rounding_modes_num[:4]:
        pyq_f = chop('h', rmode=mode)
   
        X_bit = pyq_f(X_th[:4, 0])
        print(f"{rounding_modes[mode-1]:20}: {X_bit}")

if __name__ == "__main__":
    test_fp16()

Input values:       tensor([ 1.7641,  0.3097, -0.2021,  2.4700,  0.3300])
PyTorch FP16:       tensor([ 1.7637,  0.3098, -0.2021,  2.4707,  0.3301])

Your output:
nearest             : tensor([ 1.7637,  0.3098, -0.2021,  2.4707,  0.3301])
up                  : tensor([ 1.7646,  0.3098, -0.2020,  2.4707,  0.3301])
down                : tensor([ 1.7637,  0.3096, -0.2021,  2.4688,  0.3298])
towards_zero        : tensor([ 1.7637,  0.3096, -0.2020,  2.4688,  0.3298])

Correct ones:
nearest             : tensor([ 1.7637,  0.3098, -0.2021,  2.4707])
up                  : tensor([ 1.7646,  0.3098, -0.2020,  2.4707])
down                : tensor([ 1.7637,  0.3096, -0.2021,  2.4688])
towards_zero        : tensor([ 1.7637,  0.3096, -0.2020,  2.4688])


In [20]:
import torch
import numpy as np
from typing import Tuple

class FloatPrecisionSimulator:
    """
    A class to simulate different floating-point precisions and rounding modes
    for PyTorch tensors.
    """
    def __init__(self, exponent_bits: int, mantissa_bits: int):
        self.exponent_bits = exponent_bits
        self.mantissa_bits = mantissa_bits
        self.max_exp = 2 ** (exponent_bits - 1) - 1
        self.min_exp = -self.max_exp + 1
        self.bias = 2 ** (exponent_bits - 1) - 1  # Bias for IEEE 754
        
    def _to_custom_float(self, x: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor, 
                                                        torch.Tensor, torch.Tensor, torch.Tensor]:
        """
        Initialize with specific format parameters.
        Convert to custom float representation with proper IEEE 754 handling
        
        Args:
            exponent_bits: Number of bits for exponent
            mantissa_bits: Number of bits for mantissa (significant digits)
        """
        sign = torch.sign(x)
        abs_x = torch.abs(x)
        
        # Handle special cases
        zero_mask = (abs_x == 0)
        inf_mask = torch.isinf(x)
        nan_mask = torch.isnan(x)
        
        # Calculate raw exponent and mantissa
        exponent = torch.floor(torch.log2(abs_x.clamp(min=2.0**-24)))  # Minimum denormal
        
        # Normalize mantissa to [1, 2)
        mantissa = abs_x / (2.0 ** exponent)
        
        # Handle subnormals
        subnormal_mask = (exponent < self.min_exp)
        if torch.any(subnormal_mask):
            mantissa[subnormal_mask] = abs_x[subnormal_mask] / (2.0 ** self.min_exp)
            exponent[subnormal_mask] = self.min_exp
        
        return sign, exponent + self.bias, mantissa, zero_mask, inf_mask, nan_mask
    
    def _quantize_components(self, 
                           x: torch.Tensor,
                           sign: torch.Tensor, 
                           exponent: torch.Tensor, 
                           mantissa: torch.Tensor,
                           zero_mask: torch.Tensor,
                           inf_mask: torch.Tensor,
                           nan_mask: torch.Tensor,
                           rounding_mode: str) -> torch.Tensor:
        """Quantize components according to IEEE 754 FP16 rules with various rounding modes"""
        
        # Clamp exponent to representable range (including bias)
        exp_min = 0  # 0 represents subnormals
        exp_max = 2**self.exponent_bits - 1  # 31 for FP16
        exponent = exponent.clamp(min=exp_min, max=exp_max)
        
        # Quantize mantissa
        mantissa_steps = 2 ** self.mantissa_bits
        normal_mask = (exponent > 0) & (exponent < exp_max)
        subnormal_mask = (exponent == 0)
        mantissa_normal = mantissa - 1.0  # Remove implicit leading 1 for normal numbers
        
        # Apply rounding mode
        if rounding_mode == "nearest":
            mantissa_q = torch.round(mantissa_normal * mantissa_steps) / mantissa_steps
            if torch.any(subnormal_mask):
                mantissa_q[subnormal_mask] = torch.round(mantissa[subnormal_mask] * 
                                                       mantissa_steps) / mantissa_steps
        elif rounding_mode == "up":
            mantissa_q = torch.where(sign > 0, 
                                   torch.ceil(mantissa_normal * mantissa_steps),
                                   torch.floor(mantissa_normal * mantissa_steps)) / mantissa_steps
            if torch.any(subnormal_mask):
                mantissa_q[subnormal_mask] = torch.where(sign[subnormal_mask] > 0,
                                                       torch.ceil(mantissa[subnormal_mask] * mantissa_steps),
                                                       torch.floor(mantissa[subnormal_mask] * mantissa_steps)) / mantissa_steps
        elif rounding_mode == "down":
            mantissa_q = torch.where(sign > 0,
                                   torch.floor(mantissa_normal * mantissa_steps),
                                   torch.ceil(mantissa_normal * mantissa_steps)) / mantissa_steps
            if torch.any(subnormal_mask):
                mantissa_q[subnormal_mask] = torch.where(sign[subnormal_mask] > 0,
                                                       torch.floor(mantissa[subnormal_mask] * mantissa_steps),
                                                       torch.ceil(mantissa[subnormal_mask] * mantissa_steps)) / mantissa_steps
        elif rounding_mode == "towards_zero":
            mantissa_q = torch.trunc(mantissa_normal * mantissa_steps) / mantissa_steps
            if torch.any(subnormal_mask):
                mantissa_q[subnormal_mask] = torch.trunc(mantissa[subnormal_mask] * 
                                                       mantissa_steps) / mantissa_steps
        elif rounding_mode == "stochastic_equal":
            mantissa_scaled = mantissa_normal * mantissa_steps
            floor_val = torch.floor(mantissa_scaled)
            prob = torch.rand_like(mantissa_scaled)
            mantissa_q = torch.where(prob < 0.5, floor_val, floor_val + 1) / mantissa_steps
            if torch.any(subnormal_mask):
                mantissa_scaled = mantissa[subnormal_mask] * mantissa_steps
                floor_val = torch.floor(mantissa_scaled)
                prob = torch.rand_like(mantissa_scaled)
                mantissa_q[subnormal_mask] = torch.where(prob < 0.5, floor_val, 
                                                       floor_val + 1) / mantissa_steps
        elif rounding_mode == "stochastic_proportional":
            mantissa_scaled = mantissa_normal * mantissa_steps
            floor_val = torch.floor(mantissa_scaled)
            fraction = mantissa_scaled - floor_val
            prob = torch.rand_like(mantissa_scaled)
            mantissa_q = torch.where(prob < fraction, floor_val + 1, floor_val) / mantissa_steps
            if torch.any(subnormal_mask):
                mantissa_scaled = mantissa[subnormal_mask] * mantissa_steps
                floor_val = torch.floor(mantissa_scaled)
                fraction = mantissa_scaled - floor_val
                prob = torch.rand_like(mantissa_scaled)
                mantissa_q[subnormal_mask] = torch.where(prob < fraction, floor_val + 1, 
                                                       floor_val) / mantissa_steps
        else:
            raise ValueError(f"Unsupported rounding mode: {rounding_mode}")
        
        # Reconstruct the number
        result = torch.zeros_like(x)
        
        # Normal numbers
        if torch.any(normal_mask):
            result[normal_mask] = sign[normal_mask] * (1.0 + mantissa_q[normal_mask]) * \
                                (2.0 ** (exponent[normal_mask] - self.bias))
        
        # Subnormal numbers
        if torch.any(subnormal_mask):
            result[subnormal_mask] = sign[subnormal_mask] * mantissa_q[subnormal_mask] * \
                                   (2.0 ** self.min_exp)
        
        # Special cases
        result[zero_mask] = 0.0
        result[inf_mask] = torch.sign(x[inf_mask]) * float('inf')
        result[nan_mask] = float('nan')
        
        return result

    def quantize(self, x: torch.Tensor, rounding_mode: str = "nearest") -> torch.Tensor:
        """
        Quantize a tensor to the specified precision with given rounding mode.
        
        Args:
            x: Input tensor
            rounding_mode: One of 'nearest', 'up', 'down', 'towards_zero', 
                          'stochastic_equal', 'stochastic_proportional'
        """
        sign, exponent, mantissa, zero_mask, inf_mask, nan_mask = self._to_custom_float(x)
        return self._quantize_components(x, sign, exponent, mantissa, zero_mask, inf_mask, nan_mask, rounding_mode)

# Test the implementation
def test_fp16():
    # Test values
    values = torch.tensor([1.7641, 0.3097, -0.2021, 2.4700, 0.3300])
    
    # FP16 simulator (5 exponent bits, 10 mantissa bits)
    fp16_sim = FloatPrecisionSimulator(5, 10)
    
    # Test all rounding modes
    rounding_modes = ["nearest", "up", "down", "towards_zero", 
                     "stochastic_equal", "stochastic_proportional"]
    
    # Compare with PyTorch's native FP16
    fp16_native = values.to(dtype=torch.float16).to(dtype=torch.float32)
    
    print("Input values:      ", values)
    print("PyTorch FP16:      ", fp16_native)
    print()

    print()
    rounding_modes_num = [1, 2, 3, 4, "stochastic_equal", "stochastic_proportional"]

    print("Correct ones:")
    for mode in rounding_modes_num[:4]:
        pyq_f = chop('h', rmode=mode)
        groud_truth = pyq_f(values)
        emulated = fp16_sim.quantize(values, rounding_modes[mode-1])
        assert np.array_equal(emulated, groud_truth), print("error rmode 3")
        
        print(f"{rounding_modes[mode-1]:12}, ", "Truth:", f"   {emulated}")
        print(f"{rounding_modes[mode-1]:12}, ", "Emulated:", f"{groud_truth}")
    
if __name__ == "__main__":
    test_fp16()

Input values:       tensor([ 1.7641,  0.3097, -0.2021,  2.4700,  0.3300])
PyTorch FP16:       tensor([ 1.7637,  0.3098, -0.2021,  2.4707,  0.3301])


Correct ones:
nearest     ,  Truth:    tensor([ 1.7637,  0.3098, -0.2021,  2.4707,  0.3301])
nearest     ,  Emulated: tensor([ 1.7637,  0.3098, -0.2021,  2.4707,  0.3301])
up          ,  Truth:    tensor([ 1.7646,  0.3098, -0.2020,  2.4707,  0.3301])
up          ,  Emulated: tensor([ 1.7646,  0.3098, -0.2020,  2.4707,  0.3301])
down        ,  Truth:    tensor([ 1.7637,  0.3096, -0.2021,  2.4688,  0.3298])
down        ,  Emulated: tensor([ 1.7637,  0.3096, -0.2021,  2.4688,  0.3298])
towards_zero,  Truth:    tensor([ 1.7637,  0.3096, -0.2020,  2.4688,  0.3298])
towards_zero,  Emulated: tensor([ 1.7637,  0.3096, -0.2020,  2.4688,  0.3298])


In [42]:
pychop.backend('torch', 1) # print information
pyq_f = chop('h', rmode=1)
st = time()
X_bit = pyq_f(X_th)
print("runtime:", time() - st)
print(X_bit[:5, 0])

Load Troch backend.
runtime: 1.5513670444488525
tensor([ 1.7637,  0.3098, -0.2021,  2.4707,  0.3301])


In [43]:
pychop.backend('torch', 1) # print information
pyq_f = chop('h', rmode=2)
st = time()
X_bit = pyq_f(X_th)
print("runtime:", time() - st)
print(X_bit[:5, 0])

Load Troch backend.
runtime: 1.1380090713500977
tensor([ 1.7646,  0.3098, -0.2020,  2.4707,  0.3301])


In [44]:
pychop.backend('torch', 1) # print information
pyq_f = chop('h', rmode=3)
st = time()
X_bit = pyq_f(X_th)
print("runtime:", time() - st)
print(X_bit[:5, 0])

Load Troch backend.
runtime: 1.0816121101379395
tensor([ 1.7637,  0.3096, -0.2021,  2.4688,  0.3298])


In [45]:
pychop.backend('torch', 1) # print information
pyq_f = chop('h', rmode=4)
st = time()
X_bit = pyq_f(X_th)
print("runtime:", time() - st)
print(X_bit[:5, 0])

Load Troch backend.
runtime: 1.2739830017089844
tensor([ 1.7637,  0.3096, -0.2020,  2.4688,  0.3298])


In [20]:
formats = {
    "fp32": (8, 23),    # Standard IEEE 754 float32
    "fp16": (5, 10),    # Standard IEEE 754 float16
    "bf16": (8, 7),     # Brain Float 16
    "fp8": (5, 2),      # Example 8-bit float
}
simulator = FloatPrecisionSimulator(*formats["fp16"])
X_bit = simulator.quantize(X_th, rounding_mode="nearest")
print(X_bit[:10, 0])

tensor([ 1.7644,  0.3096, -0.2021,  2.4692,  0.3302,  0.3021,  0.3712,  0.3873,
        -1.9394,  0.5616])


In [7]:
pychop.backend('jax', 1) # print information
pyq_f = chop('h')
st = time()
X_bit = pyq_f(X_jx)
print("runtime:", time() - st)
print(X_bit)

Load JAX backend.
runtime: 7.780159950256348
[[ 1.7637  0.4001  0.9785 ...  0.9292  0.2294  0.4143]
 [ 0.3098 -0.7373 -1.5371 ...  0.5171 -0.0329  1.2979]
 [-0.2021 -0.833   1.7334 ...  0.7529 -0.5811 -0.1984]
 ...
 [ 1.0742  1.1885  0.5093 ...  0.0706  0.5996 -2.4102]
 [ 0.3242 -0.0234  1.6289 ... -0.1609 -1.5977  1.415 ]
 [ 0.6348  1.3809  0.5483 ...  0.3076 -0.1108  0.8384]]


### integer quantization

In [24]:
pychop.backend('numpy')
pyq_f = pychop.quant(bits=8)
X_q = pyq_f(X_np)
X_inv = pyq_f.dequant(X_q)
linalg.norm(X_inv - X_np)

62.800703887228494

In [9]:
pychop.backend('torch')
pyq_f = pychop.quant(bits=8)
X_q = pyq_f(X_th)
X_inv = pyq_f.dequant(X_q)
linalg.norm(X_inv - X_np)

62.800703841249906

In [10]:

pychop.backend('jax')
pyq_f = pychop.quant(bits=8)
X_q = pyq_f(X_jx)
X_inv = pyq_f.dequant(X_q)
linalg.norm(X_inv - X_jx)

62.7823

### fixed point quantization

In [11]:
pychop.backend('numpy')
pyq_f = pychop.fpoint()

pyq_f(X_np)

array([[ 1.75  ,  0.375 ,  1.    , ...,  0.9375,  0.25  ,  0.4375],
       [ 0.3125, -0.75  , -1.5625, ...,  0.5   , -0.0625,  1.3125],
       [-0.1875, -0.8125,  1.75  , ...,  0.75  , -0.5625, -0.1875],
       ...,
       [ 1.0625,  1.1875,  0.5   , ...,  0.0625,  0.625 , -2.4375],
       [ 0.3125, -0.    ,  1.625 , ..., -0.1875, -1.625 ,  1.4375],
       [ 0.625 ,  1.375 ,  0.5625, ...,  0.3125, -0.125 ,  0.8125]])

In [12]:
pychop.backend('torch')
pyq_f = pychop.fpoint()
pyq_f(X_th)

tensor([[ 1.7500,  0.3750,  1.0000,  ...,  0.9375,  0.2500,  0.4375],
        [ 0.3125, -0.7500, -1.5625,  ...,  0.5000, -0.0625,  1.3125],
        [-0.1875, -0.8125,  1.7500,  ...,  0.7500, -0.5625, -0.1875],
        ...,
        [ 1.0625,  1.1875,  0.5000,  ...,  0.0625,  0.6250, -2.4375],
        [ 0.3125, -0.0000,  1.6250,  ..., -0.1875, -1.6250,  1.4375],
        [ 0.6250,  1.3750,  0.5625,  ...,  0.3125, -0.1250,  0.8125]])

In [13]:
pychop.backend('jax')
pyq_f = pychop.fpoint()
pyq_f(X_jx)

Array([[ 1.75  ,  0.375 ,  1.    , ...,  0.9375,  0.25  ,  0.4375],
       [ 0.3125, -0.75  , -1.5625, ...,  0.5   , -0.0625,  1.3125],
       [-0.1875, -0.8125,  1.75  , ...,  0.75  , -0.5625, -0.1875],
       ...,
       [ 1.0625,  1.1875,  0.5   , ...,  0.0625,  0.625 , -2.4375],
       [ 0.3125, -0.    ,  1.625 , ..., -0.1875, -1.625 ,  1.4375],
       [ 0.625 ,  1.375 ,  0.5625, ...,  0.3125, -0.125 ,  0.8125]],      dtype=float32)