In [29]:
import numpy as np
import torch
import pychop
from pychop.tch import chop
from time import time
X = torch.Tensor(np.random.randn(5000, 5000))
X

tensor([[ 2.3914, -0.9360,  1.3494,  ..., -0.1718,  1.3374, -0.4140],
        [ 1.3089, -1.4395,  1.5444,  ...,  0.9298,  0.8596,  0.4958],
        [-0.8182,  0.5194,  0.6784,  ...,  0.0836,  1.4608, -2.5341],
        ...,
        [ 0.3503,  0.6518, -0.0194,  ..., -0.4060, -1.4604,  1.7925],
        [-2.7352, -0.7808, -0.2018,  ..., -0.2029, -2.2448,  0.0753],
        [ 0.1189, -1.5567,  1.1869,  ...,  1.1703, -0.0436, -0.4877]])

In [30]:
X

tensor([[ 2.3914, -0.9360,  1.3494,  ..., -0.1718,  1.3374, -0.4140],
        [ 1.3089, -1.4395,  1.5444,  ...,  0.9298,  0.8596,  0.4958],
        [-0.8182,  0.5194,  0.6784,  ...,  0.0836,  1.4608, -2.5341],
        ...,
        [ 0.3503,  0.6518, -0.0194,  ..., -0.4060, -1.4604,  1.7925],
        [-2.7352, -0.7808, -0.2018,  ..., -0.2029, -2.2448,  0.0753],
        [ 0.1189, -1.5567,  1.1869,  ...,  1.1703, -0.0436, -0.4877]])

In [31]:
pyq_f = chop('h', copy=False)
pyq_t = chop('h', copy=True)

In [35]:
st = time()
pyq_f(X)
et = time()
et - st

1.0473763942718506

In [34]:
st = time()
pyq_t(X)
et = time()
et - st

1.0262291431427002

In [4]:
X

tensor([[-2.4896,  0.8622,  0.0065,  ..., -2.4040, -3.2924,  0.9767],
        [-0.0156,  2.3901,  1.6833,  ..., -1.0926, -0.2011, -1.0372],
        [-2.0066,  0.0746,  0.2357,  ...,  1.1607, -0.5829,  0.7842],
        ...,
        [-1.7943, -0.2826,  2.3144,  ..., -0.1833,  0.2520,  1.1333],
        [-0.1708, -0.0641, -0.1843,  ...,  0.4231, -1.9965, -0.7322],
        [-1.2726,  0.2879, -1.1815,  ..., -0.7453, -0.4590,  1.2673]])