In [10]:
import pychop
from pychop import Chop
import numpy as np
import time
np.random.seed(0)
import torch
X = torch.randn(5000, 5000) 
pychop.backend('torch', 1) # Specify different backends, e.g., jax and torch
backend = pychop.get_backend() # you can also get the current backend via .get_backend()
# One can also specify 'auto', the pychop will automatically detect the types,
# but speed will be degraded. 
 
ch = Chop(exp_bits=5, sig_bits=10, rmode=3) # half precision

st = time.time()
X_q = ch(X)
et = time.time()

print(X_q[:10, 0], f"runtime{et - st}")

Load Torch backend.
tensor([ 1.9268, -1.4482, -1.1729, -0.1912,  1.4453, -0.2249, -2.2207, -0.9629,
        -1.7705, -0.1508]) runtime0.9906771183013916


In [11]:
ch = Chop(exp_bits=5, sig_bits=10, rmode=6) # half precision

st = time.time()
X_q = ch(X)
et = time.time()

print(X_q[:10, 0], f"runtime:{et - st}")

tensor([ 1.9277, -1.4482, -1.1729, -0.1912,  1.4463, -0.2249, -2.2207, -0.9629,
        -1.7705, -0.1508]) runtime1.2062499523162842


In [12]:
ch = Chop(exp_bits=5, sig_bits=10, rmode=7) # half precision

st = time.time()
X_q = ch(X)
et = time.time()

print(X_q[:10, 0], f"runtime:{et - st}")

tensor([ 1.9268, -1.4482, -1.1729, -0.1910,  1.4453, -0.2249, -2.2188, -0.9629,
        -1.7695, -0.1508]) runtime9.420893907546997
